# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FileMaker Consulting
email: dan@filemaker.consulting
description: > # this means to ignore newlines until "baseurl:"
  Custom FileMaker development; solving complex problems with elegant solutions
  and loving every minute of it!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://filemaker.consulting" # the base hostname & protocol for your site
twitter_username: dansmith65
github_username:  dansmith65
safe: true
timezone: America/Phoenix
exclude:
  - README.md

# Build settings
markdown: kramdown

# Compress HTML settings
# http://jch.penibelst.de/
compress_html:
  clippings: all
  comments:  all
  endings:   all
  profile: false

# Compress CSS
# https://jekyllrb.com/docs/assets/
sass:
  style: compressed

# Front Matter defaults
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: "/blog/:year/:month/:title/"
      layout: post
      author: Daniel Smith
